# -*- coding: utf-8 -*-
"""Doc genie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKhVXHMVozFEkBI0AgPQ1NRp58iqjILD
"""

!pip install -q gradio transformers torch black autopep8 reportlab requests

import gradio as gr
from datetime import datetime
from pathlib import Path
import json
import re
import ast
from reportlab.lib.pagesizes import letter,A4
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,PageBreak,Table,TableStyle,Preformatted
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
import requests
import urllib.parse
import inspect


class DocGenieAnalyzer:
    """Analyze python functions and generate professional docstrings"""

    @staticmethod
    def extract_function_singnature(code):
        """Extract function name,parameters,return type from code"""
        try:
            tree=ast.parse(code)
            func_def=tree.body[0]
            if not isinstance(func_def,ast.FunctionDef):
                return None,None

            func_name =func_def.name
            params =[]

            for arg in func_def.args.args:
                param_type ="Any"
                if arg.annotation:
                    param_type =ast.unparse(arg.annotation)if hasattr(ast,'unparse')else"Any"
                params.append({
                    'name':arg.arg,
                    'type':param_type,
                    'default':None
                })
            return func_name, params
        except Exception as e:
            print(f"Error extracting function signature: {e}")
            return None, None

    @staticmethod
    def analyze_function_logic(func_def,code):
        """Deep analysis of function body to understand actual behavior"""
        try:
            body = func_def.body
            analysis = {
                'has_loops':False,
                'has_conditions':False,
                'has_return':False,
                'loop_type':[],
                'condition_type':[],
                'operations':[],
                'return_type':[],
                'variables_used':set(),
                'function_calls':[],
                'description':""
            }
            # Walk through AST
            for node in ast.walk(func_def):
                if isinstance(node,ast.For):
                  analysis['has_loops']=True
                  analysis['loop_type'].append('for')
                # Further analysis logic would go here
        except Exception as e:
            print(f"Error analyzing function logic: {e}")
            return None

    @staticmethod
    def generate_google_docstring(signature, analysis, code):
      """Generate accurate Google-style docstring"""
      summary = analysis.get('description','processes input and returns result.')
      docstring= f'   """{summary}\n'
      if signature['params']:
        docstring += '\n  Args:\n'
        for param in signature['params']:
          default_str = f"(default: {param['default']})" if param['default'] else ""
          docstring += f"    {param['name']} ({param['type']}): parameter for controlling {param['name']} behavior{default_str}.\n"
      docstring += f"\n   Returns:\n    {signature['return_type']}: The result of the computation.\n"
      docstring += '  """\n'
      return docstring

    @staticmethod
    def generate_numpy_docstring(signature, analysis, code):
      """Generate accurate NumPy-style docstring"""
      summary = analysis.get('description','processes input and returns result.')
      docstring= f'   """{summary}\n'
      if signature['params']:
        docstring += '\n  Parameters\n  ----------\n'
        for param in signature['params']:
          default_str = f", default: {param['default']}" if param['default'] else ""
          docstring += f"    {param['name']} : {param['type']}{default_str}\n"
          docstring +=f"    parameter for controlling {param['name']} behavior.\n"
      docstring += f"\n  Returns\n  -------\n    {signature['return_type']}\n"
      docstring += '  The result of the computation.\n'
      docstring += '  """\n'
      return docstring

analysis = DocGenieAnalyzer()
generation_history = []

import gradio as gr
# Placeholder functions and variables (will be properly implemented later)
def process_upload(file):
    # This function will handle file uploads and return content and status
    return "", "File uploaded successfully"

def generate_docstring(code, style):
    # This function will generate the docstring
    return f"Generated {style} docstring for:\n{code}", "Docstring generated"

def clear_history():
    # This function will clear the generation history
    global generation_history
    generation_history = []
    return "History cleared"

def download_txt():
    # This function will handle text download
    return "Download successful", gr.File(value="test.txt", label="txt file", visible=True)

def generate_whatsapp_link():
    """generate whatsapp share link"""
    if not generation_history:
        return "No documentation to share!"
    message = " doc-genie documentation\n\n"
    for i, gen in enumerate(generation_history[-3:],1):
         message += f"doc {i}:\n"
         message += f"style: {gen['style']}\n"
         message += f"{gen['code'][:60] }...\n\n"
    encoded = urllib.parse.quote(message)
    link = f"https://wa.me/?text={encoded}"
    return f" whatsapp link:\n\n{link}\n\n share with team!"

def generate_facebook_link():
   """generation facebook share link"""
   if not generation_history:
     return " no documentation to share!"
   message = f"I generated {len(generation_history)} professional python function docstrings with doc-genie! check it out!"
   encoded = urllib.parse.quote(message)
   link = f"https://www.facebook.com/sharer/sharer.php?quote={encoded}"
   return f"Facebook link:\n\n{link}\n\n Share with friends!"


export_status = gr.Textbox(label="Export Status", interactive=False, lines=1)


with gr.Blocks() as demo:
  gr.Markdown("""
## Profeassional Python Function Docstring Generator
transform your python functions with AI-powered, accurate documentation!
""")

  with gr.Row():
    with gr.Column(scale=3):
      # code input area
      gr.Markdown("## Input Function Code")
      code_input = gr.Code(
          language="python",
          label="python function",
          lines=10,
          value="def calculate_factorial(n):\n  if n == 0:\n    return 1\n  return n* calculate_factorial(n-1)"
      )


    # File Upload
    file_upload = gr.File(label=" or Upload .Py File", file_types=[".py"])
    upload_status = gr.Textbox(label="Upload Status", interactive=False, lines=1)
    def process_and_display(file):
      if file:
        content, status = process_upload(file)
        return content, status # Changed 'Status' to 'status'
      return "", "no file"
    file_upload.change(process_and_display, inputs=[file_upload], outputs=[code_input, upload_status])


  #style selection
  with gr.Row():
    docstring_style = gr.Radio(["google", "numpy"], value="google", label=" Docstring Style")
    generate_btn = gr.Button(" Generate Docstring", size="lg", variant="primary", scale=2)

  # output area
  gr.Markdown("###  Generated Docstring")
  code_output = gr.Code(
      language="python",
      label="function with docstring",
      lines=15,
      interactive=False
  )
  gen_status = gr.Textbox(label="status", interactive=False, lines=1)
  generate_btn.click(
      generate_docstring,
      inputs=[code_input, docstring_style],
      outputs=[code_output, gen_status]
  )
  with gr.Column(scale=1):
    gr.Markdown("###  controls")
    clear_btn = gr.Button("  Clear history", variant="stop", size="sm")
    clear_btn.click(clear_history, outputs=[upload_status])
    gr.Markdown("---")
    gr.Markdown("###  export")
    pdf_btn = gr.Button(" download pdf", size="sm", variant="primary")
    txt_btn = gr.Button(" download txt", size="sm", variant="primary")
    pdf_file = gr.File(label="pdf file", visible=True)
    txt_file = gr.File(label="txt file", visible=True)

demo.launch()